name: Deploy on GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build
        touch build/.nojekyll
        cp build/index.html build/404.html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.PAGES_TOKEN_VAGAS_PROGRAMACAO }}
        BRANCH: gh-pages
        FOLDER: build
